version: '3.8'

services:
  microservice:
    image: personal-data-checker:latest
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
